<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Tenants\CarWashSaaS.Tenants.Infrastructure\CarWashSaaS.Tenants.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\CarWashSaaS.Identity.Infrastructure\CarWashSaaS.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\YardOperations\CarWashSaaS.YardOperations.Infrastructure\CarWashSaaS.YardOperations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CarWashSaaS.Shared.Configuration\CarWashSaaS.Shared.Configuration.csproj" />
  </ItemGroup>

</Project>
