<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Shared\CarWashSaaS.Shared.Contracts\CarWashSaaS.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Backend\Modules\Tenants\CarWashSaaS.Tenants.Domain\CarWashSaaS.Tenants.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Backend\Modules\Identity\CarWashSaaS.Identity.Domain\CarWashSaaS.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Backend\Modules\YardOperations\CarWashSaaS.YardOperations.Domain\CarWashSaaS.YardOperations.Domain.csproj" />
  </ItemGroup>

</Project>